### ISSUE TITLE
How does the distribution work?

### ISSUE THREAD

**Issue by CGLemon** [mushrom/Budgie#1]
I am very curious about the distribution. I want to implement this method to my go engine on the further work. But I do not quite understand this work. Seem that all clients send computation result to server and get full tree from server.  I have some questions about this design.

Does it suffer the internet restrict?
How many playouts every iteration (each iteration the client will send the result once)?
How to deal with multiple clients search the same sub tree?
How to balance each client computation speed?
Is the distribution significantly strong than normal?

Thanks.

**Comment by mushrom** [comment]
Disclaimer, the distributed computation mode has sort of fallen into disrepair with the recent rewrites of the tree search, and it's been a long time since I worked on it, so I've kind of forgotten how it worked myself... This is something I plan to get back into a functional state soon, and the new implementation should be much cleaner, but yeah.

Essentially how it works:
- Each client keeps two trees, a sync tree and a working tree. The sync tree contains the last observed state of the main server tree, and the working tree is where the bot does its simulations.
- The client loop: send updates to the server (empty at the start), merge own updates into the sync tree, receive and merge updates from the server (full tree at the start) into both trees, then do playouts on the working tree.
- The server loop: Receive updates from clients, attempt to merge into the main tree. If it couldn't be merged, the client is working on a different tree, send them a full copy of the new one. Otherwise, send them the differences between the main tree and the client sync tree based on the number of updates.

Notably the client and server only send differences between the trees, sending full trees all the time is way too expensive. To answer your questions:

- If you mean whether it works over the internet, it should, although unless you have 100mb/s+ internet you'll probably have bandwidth bottlenecks... The faster the connection between the nodes the better. (This will definitely be improved with the new tree rewrite, too)
- Can do any number of playouts each iteration, specified normally with the --playouts option to the bot. I think 500/1000 each iteration was a good number when I was testing. Choosing the number of playouts is a tradeoff between spending time sending/receiving updates and working on out-of-date trees with less nodes.
- Multiple clients searching the same subtree is no problem, the updates are associative, so you end up with the same result no matter how they're added together.
- Ideally each node should have about equal speed, but assymetric nodes are not much of a problem, just means they'll consistently be working on more out-of-date trees. Not a big problem from my testing, especially since the slower nodes contribute less.
- I think it was a little bit stronger, but it's hard to say, I didn't have any test scripts at the time I was working on it, and my tree search was pretty broken. I plan to revisit this and get some hard numbers for the strength of it. Worth noting that the tree search is limited to UCT only in distributed mode, AMAF statistics are too expensive to send for each node, so it takes more playouts to reach similar levels of strength with AMAF. Also worth noting that the distributed mode for this was loosely inspired by Pachi, which has very significant strength gains when running on beefy clusters (but is also significantly stronger than budgie to begin with ;)

Hope this helps, and like I said I'll be working on this again soon, I'll put some effort into making it less obfuscated this time around :P
